### ISSUE TITLE
Use sqlalchemy instead of requests

### ISSUE THREAD

**Issue by ghost** [WEEE-Open/turbofresa#2]
With sql link configurable via .INI or JSON file, so that we can use a test DB in SQLite containing a tarallo dumpone.
`sqlalchemy` should make the code safer than using trivial http requests, but maybe it won't add any advantage asd

**Comment by ghost** [comment]
@lvps what do you think about this?

**Comment by ghost** [comment]
I have the suspect that this issue is a big stronzata since we have the bees asd

**Comment by lvps** [comment]
Yes, it's a bit unusual to say the least to use the database itself as an API. Not absurd since I think that was the point of databases some decades ago, but APIs give us more control and allow linking accounts to a LDAP server, which is a lot more complicated with MySQL accounts.

**Comment by ghost** [comment]
The fact is that `sqlalchemy` would make us save some lines of code and make it more readable.
Also, by just changing the data source you could (for example) run the program in local and use a local SQLite db for testing stuff.

**Comment by ghost** [comment]
Ok, we have bees, but... 
Turbofresa works with just ONE dedicated user that we actually don't need to manage, so `sqlalchemy` sounds better to me rather than writing our own functions to read and write from a database using http requests like a spam-bot.

**Comment by lvps** [comment]
Yeah, but do you know of a single modern piece of software that uses SQL to interact with a remote server "owned" by another software, instead of a JSON API?

This also adds more coupling between database schema and external programs: do we want to break everything everytime I want to move things around in the database? The point of the API is that it will stay stable no matter what, if I'm refactoring the tarallo code I should keep API the same. Well, at least in theory, I've changed a few things up until now, but just because nobody was using the API apart from the bot...

**Comment by ghost** [comment]
Hmm... seems reasonable.
Okay! The proper way to do this stuff and future stuff is by writing a proper `pytarallo` library

**Comment by lvps** [comment]
That would be really useful, part of the code is the bot right now, we just need to move it to its own repo.

For testing remote APIs without using production ones, we have a few choices:

* Running an instace of tarallo locally, the Vagrant config exists just for that purpose
* Make unit tests and pass a crafted Response object (or JSON-encoded string, or whatever is the input) to functions instead of actually sending a Request and waiting for the server to respond
* This tutorial: https://realpython.com/testing-third-party-apis-with-mock-servers/
* Using specific tools, like https://www.mock-server.com/
