### ISSUE TITLE
The script should also write informations to the DB

### ISSUE THREAD

**Issue by ghost** [WEEE-Open/turbofresa#7]

**Comment by lvps** [comment]
The information is:

* "Erased = yes" at the end, "Erased = no" if badblock crashes midway through, or set to no at the beginning and yes at the end
* "Surface scan passed = yes" if badblocks doesn't detect any bad block, or "no" otherwise
* "Working = no" if surface scan fails, nothing otherwise (still needs manual smartctl data check)
* The WWN, since it's available and we don't want to type things with our hands
* Saving the entire `smartctl` output somewhere (notes?) for manual inspection

**Comment by e-caste** [comment]
Generic and old issue, closing since we have newer and more specific ones.
